### ISSUE TITLE
Réparation des paquets & Nettoyage de printemps

### ISSUE THREAD

**Issue by JonathanOchej** [Devil505/elementaryos-postinstall#4]
Alors après plusieurs test, d'après ce que j'ai compris du script, il faudrait que ces 2 actions se fassent en dernier non ?

Ce n'est pas le cas pour le moment car a priori ce n'est pas la position dans le tableau de la checklist (GUI=$(zenity --list --checklist \....) qui compte mais bel et bien la position dans le script.

A mon avis il serait donc plus judicieux de déplacer ces 2 actions à la fin du script pour qu'elles se fassent bien en dernier.

**Comment by Devil505** [comment]
Merci je fais cela de suite :)
